version: "3.9"
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=<url here>
    links:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=<username here>
      - POSTGRES_PASSWORD=<password here>
      - POSTGRES_DB=<database here>
